orbs:
  gke: circleci/gcp-gke@x.y.z
version: 2.1
workflows:
  main:
    jobs:
      - gke/create-cluster:
          cluster: gcp-testing
      - gke/install:
      - run:
          name: print cluster info
          command: kubectl cluster-info

